feat: add user option for selecting enviorment
polarityio/oort pull request #2
Opened 2023-09-19 19:20 UTC by ntsmith7

2023-09-19 20:33 UTC, khitrenovich commented on server/request/authenticateRequest.js
> +  }
Note that we expose those variables as part of the integration properties and they are environment-dependent. For example, they will be different for customers running in the future EU/APJ regions. I think they should be part of the input along with client, audience etc.

2023-09-19 20:44 UTC, sarus commented on server/request/authenticateRequest.js
> +  }
> Note that we expose those variables as part of the integration properties and they are environment-dependent. For example, they will be different for customers running in the future EU/APJ regions. I think they should be part of the input along with client, audience etc.

@khitrenovich  Thank you for the feedback!  Just to clarify I think you're suggesting we expose these as two separate URL options and lean on the user to provide the correct values?

If we can avoid having users needing to know API specific URLs we try to do that but we have plenty of integrations where we set a default and then let the user override that with a different value.

Makes total sense though if different customers are going to be using different URLs and it's not consistent.  The other option is to simply provide a region selection dropdown to the user if you know what the URLs for the new regions will be.  The benefit there is that it's easier for the customer to configure but that comes at the expense of having to hard code the URLs which means it is less flexible.

2023-09-19 21:00 UTC, khitrenovich commented on server/request/authenticateRequest.js
> +  }
I always prefer flexibility. Geo-specific sites is just the most obvious example, I can think about other cases when those URLs will be different even for new tenants running in NA production/staging environments. 

I don't think adding two more inputs will make users' life much harder even without further UI enhancements. However, right now we allow copy of all those values as JSON - if you can allow "paste from JSON" on your side, this can make things a bit simpler.

2023-09-27 21:43 UTC, penwoodjon approved these changes

2023-09-29 16:24 UTC, sarus requested changes
@ntsmith7 We should update these options so the user is only specifying the base path.  As an example rather than having to specify `https://login.oort.io/oauth/token` as the `tokenUrl` they should only specify `https://login.oort.io`.

2023-09-29 18:21 UTC, khitrenovich commented
> @ntsmith7 We should update these options so the user is only specifying the base path. As an example rather than having to specify `https://login.oort.io/oauth/token` as the `tokenUrl` they should only specify `https://login.oort.io`.

I think it makes more sense to let use paste what they copied from Oort as is, without requiring additional modifications. Also, in your suggestions you are making assumptions about this path remaining constant in the future - something we cannot guarantee for the new tenants across all geographies that we will eventually support.

2023-10-09 16:26 UTC, sarus approved these changes

2023-10-09 20:20 UTC, merged